name: tests

on:
  push:
  pull_request:

jobs:
  laravel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        laravel: [ 5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.* ]
        php: [ 7.3, 7.4 ]
        include:
          - laravel: 6.*
            php: 8.0
          - laravel: 7.*
            php: 8.0
          - laravel: 8.*
            php: 8.0
    name: Tests for Laravel ${{ matrix.laravel }} on PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require laravel/framework:"${{ matrix.laravel }}" --dev --no-update
          composer install --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: ./vendor/bin/phpunit
